spring.application.name=duneverse-api
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d91m4ortqb8s739a3qug-a/postgr_oa3o
spring.datasource.username=duneverse
spring.datasource.password=uxlr5PyFAigABjV7uvF3E6XJw2RP9h45
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Seed sample job openings on startup if table empty (handled via data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
